### ISSUE TITLE
establish a leadership team

### ISSUE THREAD

**Issue by egonw** [elixir-europe/toxicology-community#19]
"All the communities that have been approved so far have a leadership team of 2-4 (generally 3) which is drawn from more than one ELIXIR node so I’d suggest you consider the leadership of your community as well."

- [ ] define role of the leadership team (in relation to the rest of the Community)
- [ ] define effort required to be put in by team members
- [ ] propose a leadership team to the Community
- [ ] officially announce the leadership team

**Comment by schymane** [comment]
Do you have an overview of which of the current community members are related to which of the different ELIXIR nodes? Worth compiling in a google sheet?

________________________________

**Comment by egonw** [comment]
No, not yet, but should happen. See https://github.com/egonw/ELIXIR-Tox/issues/20

**Comment by egonw** [comment]
First action in coming week: Rob and Egon to brainstorm about subpoint 1 and 2.

**Comment by Chris-Evelo** [comment]
There was a clear request to also contact the nodes so they can review whether
1) they have interested people in their node
2) whether institutes joining belong to the node (even though that is not obligatory they want to know
3) whether none of the participants is in direct conflict with the node

**Comment by egonw** [comment]
@Chris-Evelo, yes we got that: https://github.com/egonw/ELIXIR-Tox/issues/22 Rob and I had a telcon this Wednesday.

**Comment by egonw** [comment]
Interim team: Emma, Egon, and Rob

**Comment by egonw** [comment]
@schymane, we need to cover the first two points in this task asap. Ideally in the next week or two. The description should be half an A4 max and include anticipated workload. We will mention this team will have support. When done, we contact all previous people involved and ask them to approve (which they will).

**Comment by egonw** [comment]
We're going to send out a call for additions to the leadership team.

**Comment by egonw** [comment]
We have had applications and these are under review.
