### ISSUE TITLE
List things that needs to be added to FAIRSharing.org

### ISSUE THREAD

**Issue by egonw** [elixir-europe/toxicology-community#29]
Hi all, can everyone please have a quick look at https://fairsharing.org/Toxicology and see which toxicology related entry is missing. Please leave missing entries in the comments, or if you added something to FAIRSharing directly, leave in the comment a link to your updates in this registry.

**Comment by schymane** [comment]
I didn't see PubChem (!)
https://pubchem.ncbi.nlm.nih.gov/
Found CompTox and ChemSpider but e.g. some subsets of CompTox (e.g. TOXCAST) may be worth mentioning separately (@ChemConnector may be able to advise here)
Additional resources of note that I didn't find/see listed:
Toxic Exposome Database or T3DB: http://www.t3db.ca/
DrugBank: https://www.drugbank.ca/
Exposome Explorer: http://exposome-explorer.iarc.fr/
Blood Exposome: http://bloodexposome.org/
NORMAN Database System: https://www.norman-network.com/nds/

**Comment by marcodilger** [comment]
OECD eChemPortal: https://www.echemportal.org/echemportal/index.action
EFSA OpenFoodTox: https://www.efsa.europa.eu/en/microstrategy/openfoodtox
Danish QSAR Database: http://qsar.food.dtu.dk/
Connectivity Map: https://clue.io/cmap 

And several (all?) resources from Toxnet are missing, but it appears that Toxnet will be retired in Dezember and the databases (at least the more important ones) will be migrated to PubChem (ChemIDplus, HSDB) or PubMed (Toxline). [More Info](https://www.nlm.nih.gov/toxnet/index.html)

**Comment by egonw** [comment]
Current state with the new Toxicology collection:

![image](https://user-images.githubusercontent.com/26721/84157856-7e92e480-aa6b-11ea-9cd3-3fa1d51c677f.png)

Will be adding more suggestions and create issues for items missing (to be added).

**Comment by Chris-Evelo** [comment]
Some quick ideas after a Skype hat with Egon. I think we need to add more general Toxicology approaches, tools, services and resources: This like AOPWiki, QSAR tools, Read across services, PBPK integration platforms, PBPK parameter estimation tools, tissue and target data, toxicogenomics data collections (e.g. DiXa, TG-GATEs) and so on.

**Comment by egonw** [comment]
Current (growing) network:

![image](https://user-images.githubusercontent.com/26721/230714112-ae699d85-48fe-4d75-9054-9cbe28c12dc2.png)

**Comment by Chris-Evelo** [comment]
Hi Egon,

This is interesting, and useful. But it doesn’t really look like a toxicology resources network to me, rather a chemical one. The domain of toxicology is the interaction between chemicals and biology. It is not bad to also capture sources from chemistry and biology itself but I suppose the core set should be about that interaction. How do we get more of these in?

Best, Chris

Sent from my iPhone

On 8 Apr 2023, at 11:26, Egon Willighagen ***@***.***> wrote:

﻿

Current (growing) network:

[image]<https://user-images.githubusercontent.com/26721/230714112-ae699d85-48fe-4d75-9054-9cbe28c12dc2.png>

**Comment by Chris-Evelo** [comment]
I think we could ask project members from VHP4Safety, Ontox and such. We will in part do that anyway in a different context. Like the AOP resources and the PBPK resources that we already started to identify in VHP4Safety.

**Comment by egonw** [comment]
> I think we could ask project members from VHP4Safety, Ontox and such.

Please do bring it up in the next RL1 meeting.

**Comment by egonw** [comment]
> * Connectivity Map: https://clue.io/cmap

@marcodilger,  CM no longer exists. It's now CLUE, and pitched as a tool, but that's for bio.tools, not FAIRsharing.

**Comment by egonw** [comment]
EFSA OpenFoodTox was approved now and I added it to the Toxicology collection this morning.
